name: Daily News Aggregator

on:
  schedule:
    - cron: '45 14 * * *'  # 9:45 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-aggregator:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        
    - name: Verify credentials file (debug)
      run: |
        echo "File exists: $(test -f credentials.json && echo 'YES' || echo 'NO')"
        echo "File size: $(wc -c < credentials.json) bytes"
        echo "First 100 characters:"
        head -c 100 credentials.json
        echo ""
        echo "Last 50 characters:"
        tail -c 50 credentials.json
        echo ""
        echo "Checking JSON validity:"
        python -c "import json; print('Valid JSON:', json.load(open('credentials.json'))['installed']['client_id'][:20] + '...')" || echo "Invalid JSON"
        
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> .env
        echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> .env
        echo "PHANTOMBUSTER_API_KEY=${{ secrets.PHANTOMBUSTER_API_KEY }}" >> .env
        echo "PB_TWITTER_SEARCH_ID=${{ secrets.PB_TWITTER_SEARCH_ID }}" >> .env
        echo "PB_LINKEDIN_POSTS_ID=${{ secrets.PB_LINKEDIN_POSTS_ID }}" >> .env
        echo "GMAIL_RECIPIENTS=${{ secrets.GMAIL_RECIPIENTS }}" >> .env
        
    - name: Verify credentials file
      run: |
        echo "Credentials file size: $(wc -c < credentials.json)"
        echo "First few characters: $(head -c 50 credentials.json)"
        
    - name: Run news aggregator
      run: python main.py